### ISSUE TITLE
Add sample data x and y for tutorial

### ISSUE THREAD

**Issue by tpq** [egr95/R-codacore#1]
Maybe we can bundle an example CoDa toy data set into the package so newcomers can quickly see it working by loading something like...

```
data(coda_example)
x <- coda_example$x
y <- coda_example$y
codacore(x, y)
```

FYI bundling data should be straightforward with the usethis package https://usethis.r-lib.org/reference/use_data.html

**Comment by egr95** [comment]
Thanks for the suggestion - do you mean we should add this to the README, or bundle into codacore so that the [guide](https://egr95.github.io/R-codacore/crohn.html) no longer depends on the `selbal` package? Or both :)

**Comment by tpq** [comment]
Ah right! Yes, originally thinking add it to the README, but perhaps could replace in the guide too. It's low priority, but do think one less dependency for the end-users to install is a good thing!

**Comment by egr95** [comment]
Agreed!
