### ISSUE TITLE
cvParams defaults for codacore()

### ISSUE THREAD

**Issue by nick-youngblut** [egr95/R-codacore#12]
It would be helpful to include the `cvParams` defaults in the `codacore()` function docs. I had to check the code to find the defaults: 

```
  cvDefaults = list(
    maxCutoffs=20,
    numFolds=5
  )
```

**Comment by egr95** [comment]
Thank you Nick, agreed. I have added this into the repo and will be eventually uploaded onto the next CRAN version.
