### ISSUE TITLE
Add zero check for predict.codacore method

### ISSUE THREAD

**Issue by tpq** [egr95/R-codacore#3]
I like the check for 0s on the codacore function. I just ran into an unexpected outcome when deploying the codacore on a data set that had zeros, resulting in NaN and Inf yhat values. Perhaps we should add a check for zeros in the `predict.codacore' method?

**Comment by tpq** [comment]
Similarly, it is possible for summed log-ratio prediction to produce strange output. Is epsilon added during model deployment?

**Comment by egr95** [comment]
I have added the zeros check in the predict function. As for the SLR prediction, indeed, epsilon is added during deployment, but I'm now feeling more inclined to just removing support for zero-laden data in the SLR altogether, to avoid such 'strange' or unpredictable behavior...

**Comment by egr95** [comment]
I'm leaving warnings in the SLR case for now.
